# SITE SETTINGS
title: TDWG
description: >
  Biodiversity Information Standards (TDWG) is a non-profit organization and 
  community dedicated to developing biodiversity information standards.

# SOCIAL PROFILES
social:
  email: secretary@tdwg.org
  twitter: tdwg
  github: tdwg
  facebook: https://www.facebook.com/groups/326780777736

# THEME SETTINGS
theme: minima
remote_theme: tdwg/petridish
posts_on_home: 3
tweets_on_home: false # Ignored by custom home.html layout
archive_permalink: /news/
github_edit: true
logo: /assets/theme/images/tdwg-logo-long.svg

# BUILD SETTINGS
markdown: kramdown
plugins:                                # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed                         # Create RSS feed for posts
  - jekyll-sitemap                      # Create sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"   # Use /news/yyyy/{filename}/ as permalink for all posts
      toc: false
  - scope:
      path: "conferences/2022"
    values:
      navigation: navigation-tdwg-2022
